language: node_js
node_js:
  - "7"

before_install:
  - sudo apt-get install -qq nodejs npm python3 python3-pip
  - sudo pip install --user schul-cloud-search-tests

install:
  - npm install

script:
  - npm test

