language: node_js
node_js:
  - "7"

begfore_install:
  - sudo apt-get install -qq nodejs npm python3 python3-pip
  - pip install schul-cloud-search-tests

install:
  - npm install

script:
  - npm test

