version: '3'

services:

    wikimedia-content-adapter:
      image: wikimedia-content-adapter:latest
      build: 
        context: .
        dockerfile: Dockerfile
      ports:
        - 3000:3000
      volumes:
        - .:/app
      command: node app.js
